### ISSUE TITLE
Formatting of Readme.md

### ISSUE THREAD

**Issue by EzazAA** [EzazAA/fantastic-journey#1]

**Comment by rnihesh** [comment]
@EzazAA  Assign this to me and add hactoberfest-accepted tag , I’ll do it asap

**Comment by rnihesh** [comment]
@EzazAA  How do you want the readme to be updated ?

**Comment by rnihesh** [comment]
Hi, @EzazAA  Check and accept my merge request :)
Assign me and add hacktoberfest-accepted tag to this topic..

**Comment by rnihesh** [comment]
Didn't the readme completed ? May I update it further ?

**Comment by rnihesh** [comment]
you didnt assign me , I may get problem while, accepting my contribution to hacktober

**Comment by rnihesh** [comment]
Thanks :)
